[package]
name = "json-db"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
fake = { version = "2.9.2", features = ["derive"] }
serde-value = "0.7.0"
