[package]
name = "json-db"
version = "0.1.0"
edition = "2021"

[dependencies]
ohmydb = "1.2.3"
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.210", features = ["derive"] }
